using System.Globalization;

namespace BigPictureTV.App;

/// <summary>UI text in English and Spanish, picked from the Windows display language.</summary>
public sealed class Strings
{
    public static Strings Current { get; } =
        CultureInfo.CurrentUICulture.TwoLetterISOLanguageName == "es" ? Spanish() : English();

    public string AlreadyRunning { get; init; } = "";
    public string StateDesktop { get; init; } = "";
    public string StateTvAuto { get; init; } = "";
    public string StateTvManual { get; init; } = "";
    public string Paused { get; init; } = "";
    public string SwitchToTv { get; init; } = "";
    public string BackToDesktop { get; init; } = "";
    public string PauseAutomatic { get; init; } = "";
    public string ChooseTv { get; init; } = "";
    public string DetectAutomatically { get; init; } = "";
    public string DetectedNone { get; init; } = "";
    public string NoDisplays { get; init; } = "";
    public string StartWithWindows { get; init; } = "";
    public string OpenLogFolder { get; init; } = "";
    public string Exit { get; init; } = "";
    public string NowOnTv { get; init; } = "";
    public string NowOnDesktop { get; init; } = "";
    public string SwitchFailed { get; init; } = "";
    public string ChangedOutside { get; init; } = "";
    public string DesktopWhenHidden { get; init; } = "";
    public string Settings { get; init; } = "";
    public string SettingsTitle { get; init; } = "";
    public string Welcome { get; init; } = "";
    public string WelcomeDetected { get; init; } = "";
    public string WelcomeNotDetected { get; init; } = "";
    public string TvGroup { get; init; } = "";
    public string DetectAutomaticallyWith { get; init; } = "";
    public string Identify { get; init; } = "";
    public string InactiveInWindows { get; init; } = "";
    public string LayoutGroup { get; init; } = "";
    public string LayoutTvOnly { get; init; } = "";
    public string LayoutTvPrimary { get; init; } = "";
    public string LayoutDuplicate { get; init; } = "";
    public string GraceLabel { get; init; } = "";
    public string ExtraLabel { get; init; } = "";
    public string ExtraHint { get; init; } = "";
    public string Test { get; init; } = "";
    public string TestBusy { get; init; } = "";
    public string Save { get; init; } = "";
    public string Cancel { get; init; } = "";
    public string TestDialog { get; init; } = "";
    public string TestBack { get; init; } = "";
    public string TestSeconds { get; init; } = "";
    public string TestFailed { get; init; } = "";
    public string LeavingTvSoon { get; init; } = "";
    public string AdvancedGroup { get; init; } = "";
    public string AudioGroup { get; init; } = "";
    public string SwitchAudio { get; init; } = "";
    public string AudioAutomatic { get; init; } = "";
    public string OpenBigPictureGroup { get; init; } = "";
    public string ShortcutOpensBigPicture { get; init; } = "";
    public string OtherGroup { get; init; } = "";
    public string CheckForUpdates { get; init; } = "";
    public string OpenBigPicture { get; init; } = "";
    public string SteamNotFound { get; init; } = "";
    public string UpdateAvailable { get; init; } = "";
    public string DownloadUpdate { get; init; } = "";
    public string CopyDiagnostics { get; init; } = "";
    public string DiagnosticsCopied { get; init; } = "";
    public string ComboGroup { get; init; } = "";
    public string ComboHint { get; init; } = "";
    public string ComboRecord { get; init; } = "";
    public string ComboRumble { get; init; } = "";
    public string ComboNone { get; init; } = "";
    public string ComboRecording { get; init; } = "";
    public string ComboNoController { get; init; } = "";
    public string ComboTimeout { get; init; } = "";
    public string HotkeyGroup { get; init; } = "";
    public string HotkeyHint { get; init; } = "";
    public string HotkeyNone { get; init; } = "";
    public string HotkeyOff { get; init; } = "";
    public string HotkeyNeedsModifier { get; init; } = "";
    public string HotkeyIsEmergency { get; init; } = "";
    public string HotkeyTaken { get; init; } = "";
    public string HotkeyTakenNotify { get; init; } = "";
    public string TvMenu { get; init; } = "";
    public string TvMenuOpen { get; init; } = "";
    public string TvMenuDesktop { get; init; } = "";
    public string HintOpen { get; init; } = "";
    public string HintResume { get; init; } = "";
    public string HintCloseApp { get; init; } = "";
    public string HintBackTo { get; init; } = "";
    public string HintCloseMenu { get; init; } = "";
    public string TvMenuRunning { get; init; } = "";
    public string MenuButtonHint { get; init; } = "";
    public string MenuButtonLabel { get; init; } = "";
    public string MenuButtonNone { get; init; } = "";
    public string MenuButtonBack { get; init; } = "";
    public string MenuButtonStart { get; init; } = "";
    public string MenuButtonLS { get; init; } = "";
    public string MenuButtonRS { get; init; } = "";
    public string TvMenuOpenFailed { get; init; } = "";
    public string BrowserNotFound { get; init; } = "";
    public string TvMenuGroup { get; init; } = "";
    public string ShortcutOpensTvMenu { get; init; } = "";

    static Strings English() => new()
    {
        AlreadyRunning = "BigPictureTV is already running. Look for its icon next to the clock.",
        StateDesktop = "Desktop",
        StateTvAuto = "On the TV (Big Picture)",
        StateTvManual = "On the TV",
        Paused = "paused",
        SwitchToTv = "Switch to the TV now",
        BackToDesktop = "Back to the desktop",
        PauseAutomatic = "Pause automatic switching",
        ChooseTv = "TV",
        DetectAutomatically = "Detect automatically",
        DetectedNone = "nothing detected",
        NoDisplays = "No displays found",
        StartWithWindows = "Start with Windows",
        OpenLogFolder = "Open log folder",
        Exit = "Exit",
        NowOnTv = "Showing only the TV.",
        NowOnDesktop = "Desktop restored.",
        SwitchFailed = "Couldn't switch to the TV. Check that it's on, or pick it under TV.",
        ChangedOutside = "Windows turned the other displays back on. Big Picture will switch to the TV again next time it opens.",
        Settings = "Settings…",
        DesktopWhenHidden = "Go back to the desktop when I leave Big Picture (Windows key, Alt+Tab, minimize), not only when it closes",
        SettingsTitle = "BigPictureTV settings",
        Welcome = "Welcome! When Steam Big Picture opens, BigPictureTV moves everything to the TV, and puts your desktop back when it closes.",
        WelcomeDetected = "We think your TV is {0}. Check it below and press Test to see it in action.",
        WelcomeNotDetected = "We couldn't tell which display is the TV. Pick it below; turn the TV on first if it isn't listed.",
        TvGroup = "Which display is the TV?",
        DetectAutomaticallyWith = "Detect automatically ({0})",
        Identify = "Identify displays",
        InactiveInWindows = "off in Windows",
        LayoutGroup = "When Big Picture opens",
        LayoutTvOnly = "Use only the TV (recommended)",
        LayoutTvPrimary = "Make the TV the main display, keep the others on",
        LayoutDuplicate = "Show the same picture on every display",
        GraceLabel = "Seconds to wait after Big Picture closes:",
        ExtraLabel = "Also use the TV while these programs run (emulators, etc.):",
        ExtraHint = "Process names separated by commas, e.g. retroarch, dolphin",
        Test = "Test",
        TestBusy = "Go back to the desktop first to test.",
        Save = "Save",
        Cancel = "Cancel",
        TestDialog = "This is what happens when Big Picture opens.",
        TestBack = "Back to the desktop",
        TestSeconds = "Going back to the desktop in {0} s.",
        TestFailed = "Couldn't switch to that display. Check that it's on and connected.",
        ComboGroup = "Controller buttons to switch between the TV and the desktop",
        ComboHint = "Off by default. Press Record and hold two or more buttons together, for example both sticks (LS+RS). To switch, hold them for {0} s. Works with Xbox, PlayStation and Switch controllers (on PlayStation, LS/RS are L3/R3). Avoid Back, Start and Home: many controllers use them for their own shortcuts.",
        ComboRecord = "Record",
        ComboRumble = "Vibrate the controller when it switches",
        ComboNone = "No combo",
        ComboRecording = "Hold the buttons…",
        ComboNoController = "No controller found. Connect it and try again.",
        ComboTimeout = "No combo recorded. Hold two or more buttons together for a second.",
        AdvancedGroup = "Advanced options",
        AudioGroup = "Sound",
        SwitchAudio = "Also move the sound to the TV, and put it back afterwards",
        AudioAutomatic = "Automatic ({0})",
        OpenBigPictureGroup = "Opening Big Picture",
        ShortcutOpensBigPicture = "The keyboard shortcut and the controller combo also open Big Picture when switching to the TV",
        OtherGroup = "Other",
        CheckForUpdates = "Tell me when there is a new version (this is {0})",
        OpenBigPicture = "Open Big Picture on the TV",
        SteamNotFound = "Couldn't open Big Picture. Is Steam installed?",
        UpdateAvailable = "BigPictureTV {0} is available. Click to download it.",
        DownloadUpdate = "Download version {0}…",
        CopyDiagnostics = "Copy diagnostic info",
        DiagnosticsCopied = "Diagnostic info copied. Paste it in your GitHub issue.",
        LeavingTvSoon = "Big Picture closed. Going back to the desktop in {0} s…",
        HotkeyGroup = "Keyboard shortcut to switch between the TV and the desktop",
        HotkeyHint = "Click the box and press the combination. {0} always brings the desktop back.",
        HotkeyNone = "No shortcut",
        HotkeyOff = "(none)",
        HotkeyNeedsModifier = "Use Ctrl, Alt, Shift or Win together with another key.",
        HotkeyIsEmergency = "{0} is the emergency shortcut; pick another one.",
        HotkeyTaken = "Another program already uses {0}. Try another combination.",
        HotkeyTakenNotify = "Another program already uses {0}, so the shortcut is off. Pick another one in Settings.",
        TvMenu = "TV menu",
        TvMenuOpen = "Open the TV menu",
        TvMenuDesktop = "Desktop",
        HintOpen = "A  Open",
        HintResume = "A  Go back to it",
        HintCloseApp = "X  Close it",
        HintBackTo = "B  Back to {0}",
        HintCloseMenu = "B  Close the menu",
        TvMenuRunning = "Open",
        MenuButtonHint = "{0} opens this menu from anywhere",
        MenuButtonLabel = "Controller button that opens the TV menu (a quick tap):",
        MenuButtonNone = "None",
        MenuButtonBack = "Share / View",
        MenuButtonStart = "Options / Menu",
        MenuButtonLS = "L3 (left stick click)",
        MenuButtonRS = "R3 (right stick click)",
        TvMenuOpenFailed = "Couldn't open {0}.",
        BrowserNotFound = "Microsoft Edge wasn't found. Set another browser as BrowserPath in settings.json.",
        TvMenuGroup = "TV menu",
        ShortcutOpensTvMenu = "The keyboard shortcut and the controller combo open the TV menu (YouTube, Crunchyroll, Big Picture…)",
    };

    static Strings Spanish() => new()
    {
        AlreadyRunning = "BigPictureTV ya está abierto. Buscá su ícono junto al reloj.",
        StateDesktop = "Escritorio",
        StateTvAuto = "En la TV (Big Picture)",
        StateTvManual = "En la TV",
        Paused = "en pausa",
        SwitchToTv = "Pasar a la TV ahora",
        BackToDesktop = "Volver al escritorio",
        PauseAutomatic = "Pausar el cambio automático",
        ChooseTv = "TV",
        DetectAutomatically = "Detectar automáticamente",
        DetectedNone = "no se detectó ninguna",
        NoDisplays = "No se encontraron pantallas",
        StartWithWindows = "Iniciar con Windows",
        OpenLogFolder = "Abrir carpeta de registros",
        Exit = "Salir",
        NowOnTv = "Mostrando solo la TV.",
        NowOnDesktop = "Escritorio restaurado.",
        SwitchFailed = "No se pudo pasar a la TV. Revisá que esté encendida o elegila en el menú TV.",
        ChangedOutside = "Windows volvió a encender las otras pantallas. La próxima vez que abras Big Picture pasa a la TV de nuevo.",
        Settings = "Ajustes…",
        DesktopWhenHidden = "Volver al escritorio cuando salgo de Big Picture (tecla Windows, Alt+Tab, minimizar), no solo al cerrarlo",
        SettingsTitle = "Ajustes de BigPictureTV",
        Welcome = "¡Bienvenido! Cuando se abre Steam Big Picture, BigPictureTV pasa todo a la TV, y al cerrarlo vuelve tu escritorio.",
        WelcomeDetected = "Creemos que tu TV es {0}. Revisalo abajo y tocá Probar para verlo en acción.",
        WelcomeNotDetected = "No pudimos saber cuál pantalla es la TV. Elegila abajo; si no aparece, encendela primero.",
        TvGroup = "¿Cuál pantalla es la TV?",
        DetectAutomaticallyWith = "Detectar automáticamente ({0})",
        Identify = "Identificar pantallas",
        InactiveInWindows = "apagada en Windows",
        LayoutGroup = "Al abrir Big Picture",
        LayoutTvOnly = "Usar solo la TV (recomendado)",
        LayoutTvPrimary = "Poner la TV como principal y dejar las demás encendidas",
        LayoutDuplicate = "Mostrar lo mismo en todas las pantallas",
        GraceLabel = "Segundos a esperar después de cerrar Big Picture:",
        ExtraLabel = "Usar la TV también mientras corren estos programas (emuladores, etc.):",
        ExtraHint = "Nombres de proceso separados por comas, por ejemplo retroarch, dolphin",
        Test = "Probar",
        TestBusy = "Para probar, primero volvé al escritorio.",
        Save = "Guardar",
        Cancel = "Cancelar",
        TestDialog = "Así queda cuando se abre Big Picture.",
        TestBack = "Volver al escritorio",
        TestSeconds = "Volviendo al escritorio en {0} s.",
        TestFailed = "No se pudo pasar a esa pantalla. Revisá que esté encendida y conectada.",
        ComboGroup = "Botones del mando para cambiar entre la TV y el escritorio",
        ComboHint = "Desactivado por defecto. Tocá Grabar y mantené dos o más botones juntos, por ejemplo los dos sticks (LS+RS). Para cambiar, mantenelos {0} s. Funciona con mandos de Xbox, PlayStation y Switch (en PlayStation, LS/RS son L3/R3). Evitá Back, Start y Home: muchos mandos los usan para sus propios atajos.",
        ComboRecord = "Grabar",
        ComboRumble = "Vibrar el mando al cambiar",
        ComboNone = "Sin combo",
        ComboRecording = "Mantené los botones…",
        ComboNoController = "No se encontró ningún mando. Conectalo y probá de nuevo.",
        ComboTimeout = "No se grabó ningún combo. Mantené dos o más botones juntos un segundo.",
        AdvancedGroup = "Opciones avanzadas",
        AudioGroup = "Sonido",
        SwitchAudio = "Pasar también el sonido a la TV, y devolverlo después",
        AudioAutomatic = "Automático ({0})",
        OpenBigPictureGroup = "Abrir Big Picture",
        ShortcutOpensBigPicture = "El atajo de teclado y el combo del mando también abren Big Picture al pasar a la TV",
        OtherGroup = "Otros",
        CheckForUpdates = "Avisarme cuando haya una versión nueva (esta es la {0})",
        OpenBigPicture = "Abrir Big Picture en la TV",
        SteamNotFound = "No se pudo abrir Big Picture. ¿Está instalado Steam?",
        UpdateAvailable = "Hay una versión nueva de BigPictureTV ({0}). Hacé clic para descargarla.",
        DownloadUpdate = "Descargar la versión {0}…",
        CopyDiagnostics = "Copiar info de diagnóstico",
        DiagnosticsCopied = "Info de diagnóstico copiada. Pegala en tu reporte de GitHub.",
        LeavingTvSoon = "Se cerró Big Picture. Volviendo al escritorio en {0} s…",
        HotkeyGroup = "Atajo de teclado para cambiar entre la TV y el escritorio",
        HotkeyHint = "Hacé clic en el cuadro y presioná la combinación. {0} siempre vuelve al escritorio.",
        HotkeyNone = "Sin atajo",
        HotkeyOff = "(ninguno)",
        HotkeyNeedsModifier = "Usá Ctrl, Alt, Shift o Win junto con otra tecla.",
        HotkeyIsEmergency = "{0} es el atajo de emergencia; elegí otro.",
        HotkeyTaken = "Otro programa ya usa {0}. Probá otra combinación.",
        HotkeyTakenNotify = "Otro programa ya usa {0}, así que el atajo quedó desactivado. Elegí otro en Ajustes.",
        TvMenu = "Menú TV",
        TvMenuOpen = "Abrir el Menú TV",
        TvMenuDesktop = "Escritorio",
        HintOpen = "A  Abrir",
        HintResume = "A  Volver a la app",
        HintCloseApp = "X  Cerrarla",
        HintBackTo = "B  Volver a {0}",
        HintCloseMenu = "B  Cerrar el menú",
        TvMenuRunning = "Abierta",
        MenuButtonHint = "{0} abre este menú desde cualquier lado",
        MenuButtonLabel = "Botón del mando que abre el Menú TV (un toque):",
        MenuButtonNone = "Ninguno",
        MenuButtonBack = "Share / View",
        MenuButtonStart = "Options / Menu",
        MenuButtonLS = "L3 (clic del stick izquierdo)",
        MenuButtonRS = "R3 (clic del stick derecho)",
        TvMenuOpenFailed = "No se pudo abrir {0}.",
        BrowserNotFound = "No se encontró Microsoft Edge. Poné otro navegador en BrowserPath dentro de settings.json.",
        TvMenuGroup = "Menú TV",
        ShortcutOpensTvMenu = "El atajo de teclado y el combo del mando abren el Menú TV (YouTube, Crunchyroll, Big Picture…)",
    };
}
